# Generated by Django 4.2.30 on 2026-05-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turno', models.CharField(max_length=30, unique=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'db_table': 'caja_turno',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('requiere_referencia', models.BooleanField(default=False)),
                ('permite_vuelto', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PAGADO', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caja_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='caja.cajaturno')),
            ],
            options={
                'verbose_name': 'Pago',
                'db_table': 'pago',
            },
        ),
    ]
