# Generated by Django 4.2.30 on 2026-05-02 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaturno',
            name='cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_caja', to=settings.AUTH_USER_MODEL),
        ),
    ]
