# Generated by Django 4.2.30 on 2026-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_comanda_nombre_cliente'),
        ('caja', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaturno',
            name='arqueo_fisico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto contado físicamente al cerrar', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia entre sistema y físico', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='punto_caja',
            field=models.CharField(choices=[('PLANTA_BAJA', 'Planta Baja'), ('PISO_1', 'Piso 1'), ('TERRAZA', 'Terraza')], default='PLANTA_BAJA', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='lineas_pagadas',
            field=models.ManyToManyField(blank=True, related_name='pagos', to='comandas.lineacomanda'),
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID único para agrupar pagos de una misma transacción', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado'), ('PERDIDA', 'Pérdida (No pagó)')], default='PAGADO', max_length=20),
        ),
    ]
