# Generated by Django 4.2.30 on 2026-05-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de mesa')),
                ('capacidad', models.PositiveSmallIntegerField(default=4, verbose_name='Capacidad (personas)')),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'En Limpieza')], default='LIBRE', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='mesas.zona')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'mesa',
                'ordering': ['zona', 'numero'],
                'unique_together': {('zona', 'numero')},
            },
        ),
    ]
