# Generated by Django 4.2.30 on 2026-05-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesa_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionMesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mesa_principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='union_como_principal', to='mesas.mesa', verbose_name='Mesa Principal')),
                ('mesas_secundarias', models.ManyToManyField(blank=True, related_name='uniones_como_secundaria', to='mesas.mesa', verbose_name='Mesas Secundarias')),
            ],
            options={
                'verbose_name': 'Unión de Mesas',
                'verbose_name_plural': 'Uniones de Mesas',
                'db_table': 'union_mesas',
            },
        ),
    ]
