# Generated by Django 4.2.30 on 2026-05-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_add_union_mesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='unionmesas',
            name='capacidad_personalizada',
            field=models.IntegerField(blank=True, help_text='Si se establece, anula la suma automática de las capacidades.', null=True, verbose_name='Capacidad Personalizada'),
        ),
    ]
