# Generated by Django 4.2.30 on 2026-05-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_insumo_stock_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_real',
            field=models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.insumo'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['activo', 'stock_real'], name='insumo_activo_stock_idx'),
        ),
    ]
