# Generated by Django 4.2.30 on 2026-05-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_alter_insumo_activo_alter_insumo_stock_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al proveedor'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'db_table': 'orden_compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'orden_compra_item',
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('PROTEINA', 'Proteínas'), ('VEGETAL', 'Vegetales'), ('BEBIDA', 'Bebidas'), ('SECO', 'Secos / Abarrotes'), ('LACTEO', 'Lácteos'), ('CONDIMENTO', 'Condimentos'), ('OTRO', 'Otros')], db_index=True, default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='causa_merma',
            field=models.CharField(blank=True, choices=[('VENCIDO', 'Vencido'), ('DAÑADO', 'Dañado'), ('DERRAME', 'Derrame'), ('ROBO', 'Robo / Faltante'), ('ERROR', 'Error de preparación'), ('OTRO', 'Otro')], help_text='Solo aplica cuando tipo_movimiento=MERMA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('CONSUMO', 'Consumo (Cocina)'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('MERMA', 'Merma / Pérdida')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['categoria', 'activo'], name='insumo_categoria_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['insumo', '-created_at'], name='mov_insumo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento', '-created_at'], name='mov_tipo_fecha_idx'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_items', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompraitem',
            unique_together={('orden', 'insumo')},
        ),
    ]
