# Generated by Django 4.2.30 on 2026-07-16 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def completar_motivo_inactivos(apps, schema_editor):
    Insumo = apps.get_model('inventario', 'Insumo')
    Insumo.objects.filter(activo=False, motivo_inactivacion='').update(
        motivo_inactivacion='Inactivado antes de requerir motivo obligatorio.'
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0008_magnitudes_y_conversiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='inactivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='inactivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos_inactivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='motivo_inactivacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(
            completar_motivo_inactivos, migrations.RunPython.noop
        ),
        migrations.CreateModel(
            name='InsumoCambioMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_conversion', models.DecimalField(decimal_places=8, max_digits=18)),
                ('motivo', models.TextField()),
                ('valores_anteriores', models.JSONField(default=dict)),
                ('valores_nuevos', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_medida', to='inventario.insumo')),
                ('magnitud_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.magnitudmedida')),
                ('magnitud_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.magnitudmedida')),
                ('unidad_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.unidadmedida')),
                ('unidad_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.unidadmedida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_medida_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correccion de medida de insumo',
                'db_table': 'insumo_cambio_medida',
                'ordering': ('-created_at',),
            },
        ),
    ]
