from decimal import Decimal

from django.conf import settings


ACCIONES_AUDITABLES = frozenset({
    'COMANDA_PLATO_ANULADO',
    'COMANDA_PLATO_ANULADO_POST_COCINA',
    'COMANDA_ANULADA',
    'COMANDA_ANULADA_CON_PRODUCCION',
    'CAJA_TURNO_ABIERTO',
    'CAJA_TURNO_CERRADO',
    'CAJA_DESCUADRE_DETECTADO',
    'CAJA_CIERRE_FORZADO',
    'CAJA_TURNO_REABIERTO',
    'CAJA_VENTA_PERDIDA_REGISTRADA',
    'PAGO_METODO_MODIFICADO',
    'PAGO_ANULADO',
    'PAGO_SOFT_DELETE',
    'INVENTARIO_INSUMO_AGOTADO_SIN_REPOSICION',
    'INVENTARIO_STOCK_BAJO_PERSISTENTE',
    'INVENTARIO_MERMA_ELEVADA',
    'INVENTARIO_EGRESO_INCOHERENTE',
    'INVENTARIO_AJUSTE_MANUAL_ELEVADO',
    'INVENTARIO_AJUSTES_REPETIDOS',
    'INVENTARIO_LOTE_REPETIDO',
    'INVENTARIO_COSTO_UNITARIO_VARIACION_ALTA',
    'INVENTARIO_STOCK_INSUFICIENTE_REITERADO',
    'RECETA_MODIFICADA',
    'RECETA_INSUMO_ELIMINADO',
    'PLATO_DESHABILITADO_STOCK',
    'PLATO_REACTIVADO_SIN_STOCK',
    'PLATO_MODIFICADO',
    'PLATO_PRECIO_MODIFICADO',
    'PLATO_CAMBIO_MASIVO_PRECIOS',
    'PLATO_SOFT_DELETE',
    'LOGIN_FALLIDO_REITERADO',
    'USUARIO_CREADO',
    'USUARIO_ROL_MODIFICADO',
    'USUARIO_ESCALAMIENTO_PRIVILEGIOS',
    'USUARIO_DESACTIVADO',
    'USUARIO_REACTIVADO',
    'USUARIO_PASSWORD_MODIFICADO',
    'ACCESO_DENEGADO',
    'AUDITORIA_ACCESO_PANEL',
    'AUDITORIA_EXPORTADA',
})


ACCIONES_CON_MOTIVO_OBLIGATORIO = frozenset({
    'COMANDA_PLATO_ANULADO',
    'COMANDA_PLATO_ANULADO_POST_COCINA',
    'COMANDA_ANULADA',
    'COMANDA_ANULADA_CON_PRODUCCION',
    'PAGO_ANULADO',
    'PLATO_PRECIO_MODIFICADO',
    'PLATO_CAMBIO_MASIVO_PRECIOS',
    'RECETA_MODIFICADA',
    'RECETA_INSUMO_ELIMINADO',
    'CAJA_CIERRE_FORZADO',
    'CAJA_TURNO_REABIERTO',
    'CAJA_VENTA_PERDIDA_REGISTRADA',
    'PAGO_SOFT_DELETE',
    'PLATO_SOFT_DELETE',
    'INVENTARIO_AJUSTE_MANUAL_ELEVADO',
})


UMBRALES_AUDITORIA = {
    'CAJA_MARGEN_DESCUADRE': Decimal('1.00'),
    'INVENTARIO_AGOTADO_CRITICO_HORAS': 24,
    'INVENTARIO_AGOTADO_NO_CRITICO_HORAS': 48,
    'INVENTARIO_STOCK_BAJO_DIAS': 3,
    'INVENTARIO_MERMA_PORCENTAJE': Decimal('5'),
    'INVENTARIO_EGRESO_DESVIACION_PORCENTAJE': Decimal('10'),
    'INVENTARIO_AJUSTE_PORCENTAJE': Decimal('5'),
    'INVENTARIO_AJUSTE_IMPACTO': Decimal('100'),
    'INVENTARIO_AJUSTES_REPETIDOS_CANTIDAD': 3,
    'INVENTARIO_AJUSTES_REPETIDOS_HORAS': 24,
    'INVENTARIO_VARIACION_COSTO_PORCENTAJE': Decimal('20'),
    'INVENTARIO_BLOQUEOS_STOCK_TURNO': 5,
    'LOGIN_FALLIDOS_CANTIDAD': 5,
    'LOGIN_FALLIDOS_VENTANA_MINUTOS': 10,
    'PRECIO_CAMBIO_MASIVO_CANTIDAD': 2,
    'PRECIO_VARIACION_ALTA_PORCENTAJE': Decimal('20'),
    'ACCESO_DENEGADO_DEDUP_MINUTOS': 1,
}


JERARQUIA_ROLES = {
    'MOZO': 10,
    'COCINERO': 20,
    'CAJERO': 30,
    'ADMIN': 100,
}


def obtener_umbral(nombre):
    """Obtiene un umbral, permitiendo sobrescribirlo desde settings."""
    personalizados = getattr(settings, 'AUDITORIA_UMBRALES', {})
    return personalizados.get(nombre, UMBRALES_AUDITORIA[nombre])
