# Generated by Django 4.2.30 on 2026-05-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_dni_usuario_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('MANANA', 'Turno Mañana'), ('TARDE', 'Turno Tarde'), ('NOCHE', 'Turno Noche')], default='MANANA', max_length=20),
        ),
    ]
