# Generated by Django 4.2.30 on 2026-06-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('usuarios', '0004_usuario_turno'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AuditLog',
                ),
            ],
            database_operations=[],
        ),
    ]
