# Generated by Django 4.2.30 on 2026-05-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_comanda', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PREPARACION', 'En Preparación'), ('LISTA', 'Lista para cobrar'), ('COBRADA', 'Cobrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion_general', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'db_table': 'comanda',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='LineaComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREP', 'En Preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('tiempo_estimado_min', models.PositiveSmallIntegerField(default=0)),
                ('fecha_envio_cocina', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_prep', models.DateTimeField(blank=True, null=True)),
                ('fecha_listo', models.DateTimeField(blank=True, null=True)),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='comandas.comanda')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='menu.plato')),
            ],
            options={
                'verbose_name': 'Línea de Comanda',
                'verbose_name_plural': 'Líneas de Comanda',
                'db_table': 'linea_comanda',
            },
        ),
        migrations.CreateModel(
            name='ComandaHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('origen', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('KDS', 'KDS')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='comandas.comanda')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'comanda_historial_estado',
            },
        ),
    ]
