# Generated by Django 4.2.30 on 2026-05-02 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0001_initial'),
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comandahistorialestado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='mesas.mesa'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='mozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to=settings.AUTH_USER_MODEL),
        ),
    ]
