# Generated by Django 4.2.30 on 2026-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
        ('comandas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='mesas_adicionales',
            field=models.ManyToManyField(blank=True, related_name='uniones_adicionales', to='mesas.mesa'),
        ),
    ]
