# Generated by Django 4.2.30 on 2026-05-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_comanda_mesas_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
