# Generated by Django 4.2.30 on 2026-07-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_insumo_inactivado_en_insumo_inactivado_por_and_more'),
        ('comandas', '0005_lineacomanda_auditoria_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacomanda',
            name='insumos_excluidos',
            field=models.ManyToManyField(blank=True, related_name='lineas_excluidas', to='inventario.insumo'),
        ),
    ]
