# Generated by Django 4.2.30 on 2026-06-28 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def ejecutar_sql_si_es_postgres(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('''
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS rol varchar(50) NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS modulo varchar(50) NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS codigo_evento varchar(100) NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS severidad varchar(20) NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS descripcion text NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS motivo text NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS impacto_economico_estimado numeric(12, 2) NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS ruta varchar(255) NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS metodo_http varchar(10) NULL;
                ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS estado_revision varchar(20) NULL;
            ''')
            cursor.execute('''
                UPDATE audit_log AS audit
                SET rol = roles.nombre
                FROM usuario AS users
                JOIN rol AS roles ON roles.id = users.rol_id
                WHERE audit.usuario_id = users.id AND audit.rol IS NULL;
            ''')
            cursor.execute('''
                UPDATE audit_log
                SET modulo = COALESCE(NULLIF(entidad, ''), 'GENERAL'),
                    codigo_evento = COALESCE(NULLIF(accion, ''), 'EVENTO_LEGADO'),
                    severidad = COALESCE(severidad, 'INFO'),
                    descripcion = COALESCE(descripcion, ''),
                    estado_revision = COALESCE(estado_revision, 'PENDIENTE');
            ''')
            cursor.execute('''
                ALTER TABLE audit_log ALTER COLUMN modulo SET NOT NULL;
                ALTER TABLE audit_log ALTER COLUMN codigo_evento SET NOT NULL;
                ALTER TABLE audit_log ALTER COLUMN severidad SET NOT NULL;
                ALTER TABLE audit_log ALTER COLUMN descripcion SET NOT NULL;
                ALTER TABLE audit_log ALTER COLUMN estado_revision SET NOT NULL;
            ''')


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
        ('usuarios', '0004_usuario_turno'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('rol', models.CharField(blank=True, max_length=50, null=True)),
                        ('modulo', models.CharField(blank=True, default='', max_length=50)),
                        ('codigo_evento', models.CharField(blank=True, default='', max_length=100)),
                        ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('ADVERTENCIA', 'Advertencia'), ('CRITICA', 'Critica')], default='INFO', max_length=20)),
                        ('accion', models.CharField(max_length=50)),
                        ('entidad', models.CharField(max_length=50)),
                        ('entidad_id', models.BigIntegerField()),
                        ('descripcion', models.TextField(blank=True, default='')),
                        ('motivo', models.TextField(blank=True, null=True)),
                        ('detalle_anterior', models.JSONField(blank=True, null=True)),
                        ('detalle_nuevo', models.JSONField(blank=True, null=True)),
                        ('impacto_economico_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                        ('ip', models.GenericIPAddressField(blank=True, null=True)),
                        ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                        ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                        ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                        ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                        ('estado_revision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revision'), ('REVISADO', 'Revisado'), ('DESCARTADO', 'Descartado')], default='PENDIENTE', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Log de auditoria',
                        'verbose_name_plural': 'Logs de auditoria',
                        'db_table': 'audit_log',
                        'ordering': ['-fecha_evento'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(ejecutar_sql_si_es_postgres, reverse_code=migrations.RunPython.noop),
            ],
        ),
    ]
