# Generated by Django 4.2.30 on 2026-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='estado_resultado',
            field=models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('DENEGADO', 'Denegado')], default='EXITOSO', max_length=20),
        ),
    ]
